# Generated by Django 3.2.16 on 2022-11-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecard',
            name='tag',
            field=models.ManyToManyField(related_name='tag_message', to='sns_main.Tag'),
        ),
    ]
