# Generated by Django 3.2.16 on 2022-12-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagecard',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='images/-3513275928292315771/'),
        ),
    ]
