# Generated by Django 3.2.16 on 2022-12-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns_main', '0002_alter_messagecard_head_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagecard',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='messagecard',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='images/-7798363426706062213/'),
        ),
    ]
