# Generated by Django 3.2.16 on 2022-12-01 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns_main', '0003_auto_20221201_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['created_at']},
        ),
    ]
