# Generated by Django 3.2.16 on 2022-12-01 16:35

from django.db import migrations, models
import sns_main.models


class Migration(migrations.Migration):

    dependencies = [
        ('sns_main', '0004_alter_reply_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and -/_ only.', max_length=150, unique=True, validators=[sns_main.models.UsernameValidator()], verbose_name='username'),
        ),
    ]
