# Generated by Django 3.2.16 on 2022-12-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns_main', '0007_alter_messagecard_head_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagecard',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='images/-8562962701985528715/'),
        ),
    ]
