# Generated by Django 3.2.16 on 2022-12-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns_main', '0008_alter_messagecard_head_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagecard',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='messagecard',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='images/420571106449648321/'),
        ),
    ]
