# Generated by Django 3.2.16 on 2022-12-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns_main', '0009_auto_20221204_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagecard',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='images/-871806397694020516/'),
        ),
    ]
